FROM debian:8
MAINTAINER Peter Souter <p.morsou@gmail.com>
LABEL puppet_install_shell="debian_8"
RUN apt-get update --yes
RUN apt-get install curl apt-utils --yes
COPY ./install_puppet.sh /
COPY ./install_puppet_agent.sh /
COPY ./install_puppet_5_agent.sh /
