on: [push, pull_request]
name: acceptance tests
jobs:
  Linux:
    strategy:
      matrix:
        os: ["ubuntu:latest", "debian:latest", "fedora:latest", "centos:7"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run install script 
      run: |  
        sudo bash ./install_puppet_7_agent.sh
    - name: Test puppet is installed
      run: |
        /opt/puppetlabs/bin/puppet --version